<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttributeValuesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $user = \App\User::orderBy('id')->first();
        \DB::table('attribute_values')->insert(array (
            0 =>
            array (
                'id' => 33,
                'entity_id' => 5,
                'attribute_id' => 9,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:12',
                'updated_at' => '2017-12-31 16:15:12',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '{"B": 10, "H": 3, "T": 1.5, "unit": "cm"}',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            1 =>
            array (
                'id' => 34,
                'entity_id' => 5,
                'attribute_id' => 12,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => '3.5',
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:12',
                'updated_at' => '2017-12-31 16:15:12',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            2 =>
            array (
                'id' => 35,
                'entity_id' => 5,
                'attribute_id' => 18,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => 6,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:12',
                'updated_at' => '2017-12-31 16:15:12',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            3 =>
            array (
                'id' => 36,
                'entity_id' => 4,
                'attribute_id' => 2,
                'str_val' => NULL,
                'int_val' => 100,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:19',
                'updated_at' => '2017-12-31 16:15:19',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            4 =>
            array (
                'id' => 37,
                'entity_id' => 4,
                'attribute_id' => 4,
                'str_val' => NULL,
                'int_val' => 1,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:19',
                'updated_at' => '2017-12-31 16:15:19',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            5 =>
            array (
                'id' => 39,
                'entity_id' => 4,
                'attribute_id' => 9,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:19',
                'updated_at' => '2017-12-31 16:15:19',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '{"B": 45, "H": 40, "unit": "cm"}',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            6 =>
            array (
                'id' => 40,
                'entity_id' => 4,
                'attribute_id' => 11,
                'str_val' => NULL,
                'int_val' => 10,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:19',
                'updated_at' => '2017-12-31 16:15:19',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            7 =>
            array (
                'id' => 41,
                'entity_id' => 4,
                'attribute_id' => 12,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => '500',
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:19',
                'updated_at' => '2017-12-31 16:15:19',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            8 =>
            array (
                'id' => 42,
                'entity_id' => 3,
                'attribute_id' => 2,
                'str_val' => NULL,
                'int_val' => 35,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:25',
                'updated_at' => '2017-12-31 16:15:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            9 =>
            array (
                'id' => 43,
                'entity_id' => 3,
                'attribute_id' => 4,
                'str_val' => NULL,
                'int_val' => 1,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:25',
                'updated_at' => '2017-12-31 16:15:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            10 =>
            array (
                'id' => 46,
                'entity_id' => 3,
                'attribute_id' => 9,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:25',
                'updated_at' => '2017-12-31 16:15:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '{"B": 4, "H": 5, "unit": "cm"}',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            11 =>
            array (
                'id' => 47,
                'entity_id' => 3,
                'attribute_id' => 11,
                'str_val' => NULL,
                'int_val' => 7,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:25',
                'updated_at' => '2017-12-31 16:15:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            12 =>
            array (
                'id' => 48,
                'entity_id' => 3,
                'attribute_id' => 12,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => '12.5',
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:25',
                'updated_at' => '2017-12-31 16:15:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            13 =>
            array (
                'id' => 49,
                'entity_id' => 8,
                'attribute_id' => 2,
                'str_val' => NULL,
                'int_val' => 40,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:47',
                'updated_at' => '2017-12-31 16:15:47',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            14 =>
            array (
                'id' => 51,
                'entity_id' => 8,
                'attribute_id' => 9,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:47',
                'updated_at' => '2017-12-31 16:15:47',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '{"B": 10, "H": 5, "unit": "cm"}',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            15 =>
            array (
                'id' => 52,
                'entity_id' => 8,
                'attribute_id' => 11,
                'str_val' => NULL,
                'int_val' => 7,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:47',
                'updated_at' => '2017-12-31 16:15:47',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            16 =>
            array (
                'id' => 53,
                'entity_id' => 8,
                'attribute_id' => 12,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => '5',
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:47',
                'updated_at' => '2017-12-31 16:15:47',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            17 =>
            array (
                'id' => 60,
                'entity_id' => 2,
                'attribute_id' => 14,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => 'https://spacialist.escience.uni-tuebingen.de/<user-project>/graben#20171220110123',
                'created_at' => '2017-12-31 16:17:57',
                'updated_at' => '2017-12-31 16:17:57',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            18 =>
            array (
                'id' => 61,
                'entity_id' => 2,
                'attribute_id' => 16,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:17:57',
                'updated_at' => '2017-12-31 16:17:57',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => NULL,
                'geography_val' => '0101000020E6100000D7A3703D0AD721409A99999999394840',
                'dt_val' => NULL,
            ),
            19 =>
            array (
                'id' => 62,
                'entity_id' => 2,
                'attribute_id' => 17,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:17:57',
                'updated_at' => '2019-01-21 09:45:22',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '{"end": 300, "epoch": {"concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/eisenzeit#20171220165409"}, "start": 340, "endLabel": "bc", "startLabel": "bc"}',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            20 =>
            array (
                'id' => 69,
                'entity_id' => 1,
                'attribute_id' => 15,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:03:38',
                'updated_at' => '2017-12-31 16:03:38',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '["Fundstelle A"]',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            21 =>
            array (
                'id' => 70,
                'entity_id' => 7,
                'attribute_id' => 15,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:18:25',
                'updated_at' => '2017-12-31 16:18:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '["Kirchberg"]',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            22 =>
            array (
                'id' => 71,
                'entity_id' => 4,
                'attribute_id' => 5,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:19',
                'updated_at' => '2017-12-31 16:15:19',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '[{"6": {"id": 37, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/schulter#20171220105500"}, "7": {"id": 40, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/riefung#20171220105513"}}]',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            23 =>
            array (
                'id' => 72,
                'entity_id' => 3,
                'attribute_id' => 5,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:25',
                'updated_at' => '2017-12-31 16:15:25',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '[{"6": {"id": 35, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/rand#20171220105447"}, "7": {"id": 40, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/riefung#20171220105513"}}, {"6": {"id": 35, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/rand#20171220105447"}, "7": {"id": 41, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/kammeindruck#20171220105520"}}]',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
            24 =>
            array (
                'id' => 73,
                'entity_id' => 8,
                'attribute_id' => 5,
                'str_val' => NULL,
                'int_val' => NULL,
                'dbl_val' => NULL,
                'entity_val' => NULL,
                'thesaurus_val' => NULL,
                'created_at' => '2017-12-31 16:15:47',
                'updated_at' => '2017-12-31 16:15:47',
                'certainty' => 100,
                'user_id' => $user->id,
                'json_val' => '[{"6": {"id": 39, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/boden#20171220105508"}, "7": {"id": 41, "concept_url": "https://spacialist.escience.uni-tuebingen.de/<user-project>/kammeindruck#20171220105520"}}]',
                'geography_val' => NULL,
                'dt_val' => NULL,
            ),
        ));
    }
}
