<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AvailableLayersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('available_layers')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Unlinked',
                'url' => '',
                'type' => 'unlinked',
                'subdomains' => NULL,
                'attribution' => NULL,
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => true,
                'created_at' => '2017-12-20 09:47:17',
                'updated_at' => '2017-12-20 09:47:17',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 1,
                'entity_type_id' => NULL,
                'color' => '#E5F9CE',
            ),
            1 =>
            array (
                'id' => 4,
                'name' => '',
                'url' => '',
                'type' => 'Point',
                'subdomains' => NULL,
                'attribution' => NULL,
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => true,
                'created_at' => '2017-12-20 10:03:06',
                'updated_at' => '2017-12-20 10:03:06',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 2,
                'entity_type_id' => 3,
                'color' => '#AEA628',
            ),
            2 =>
            array (
                'id' => 5,
                'name' => '',
                'url' => '',
                'type' => 'Polygon',
                'subdomains' => NULL,
                'attribution' => NULL,
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => true,
                'created_at' => '2017-12-20 10:03:15',
                'updated_at' => '2017-12-20 10:03:15',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 3,
                'entity_type_id' => 4,
                'color' => '#3E798B',
            ),
            3 =>
            array (
                'id' => 6,
                'name' => '',
                'url' => '',
                'type' => 'Point',
                'subdomains' => NULL,
                'attribution' => NULL,
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => true,
                'created_at' => '2017-12-20 10:03:23',
                'updated_at' => '2017-12-20 10:03:23',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 4,
                'entity_type_id' => 5,
                'color' => '#E2707D',
            ),
            4 =>
            array (
                'id' => 7,
                'name' => '',
                'url' => '',
                'type' => 'Point',
                'subdomains' => NULL,
                'attribution' => NULL,
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => true,
                'created_at' => '2017-12-20 10:03:30',
                'updated_at' => '2017-12-20 10:03:30',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 5,
                'entity_type_id' => 6,
                'color' => '#58077C',
            ),
            5 =>
            array (
                'id' => 8,
                'name' => '',
                'url' => '',
                'type' => 'Point',
                'subdomains' => NULL,
                'attribution' => NULL,
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => true,
                'created_at' => '2017-12-20 16:57:41',
                'updated_at' => '2017-12-20 16:57:41',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 6,
                'entity_type_id' => 7,
                'color' => '#A6F121',
            ),
            6 =>
            array (
                'id' => 9,
                'name' => 'OpenStreetMap',
                'url' => 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                'type' => 'xyz',
                'subdomains' => NULL,
                'attribution' => '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => true,
                'is_overlay' => false,
                'created_at' => '2017-12-31 16:05:05',
                'updated_at' => '2017-12-31 16:06:25',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 1,
                'entity_type_id' => NULL,
                'color' => '#05EE1D',
            ),
            7 =>
            array (
                'id' => 10,
                'name' => 'OSM',
                'url' => 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                'type' => 'xyz',
                'subdomains' => NULL,
                'attribution' => '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
                'opacity' => '1',
                'layers' => NULL,
                'styles' => NULL,
                'format' => NULL,
                'version' => NULL,
                'visible' => false,
                'is_overlay' => false,
                'created_at' => '2017-12-31 16:05:05',
                'updated_at' => '2017-12-31 16:06:25',
                'api_key' => NULL,
                'layer_type' => NULL,
                'position' => 2,
                'entity_type_id' => NULL,
                'color' => '#15D892',
            )
        ));
    }
}
