<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BibliographyTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $user = \App\User::orderBy('id')->first();
        \DB::table('bibliography')->insert(array (
            0 =>
            array (
                'id' => 1318,
                'entry_type' => 'article',
                'citekey' => 'Sh:1',
                'title' => '{Stable theories}',
                'author' => 'Shelah, Saharon',
                'editor' => NULL,
                'journal' => 'Israel Journal of Mathematics',
                'year' => '1969',
                'pages' => '187--202',
                'volume' => '7',
                'number' => NULL,
                'booktitle' => NULL,
                'publisher' => NULL,
                'address' => NULL,
                'misc' => NULL,
                'howpublished' => NULL,
                'annote' => NULL,
                'chapter' => NULL,
                'crossref' => NULL,
                'edition' => NULL,
                'institution' => NULL,
                'key' => NULL,
                'month' => NULL,
                'note' => NULL,
                'organization' => NULL,
                'school' => NULL,
                'series' => NULL,
                'user_id' => $user->id,
                'created_at' => '2019-03-08 13:35:01',
                'updated_at' => '2019-03-08 13:35:01',
            ),
            1 =>
            array (
                'id' => 1319,
                'entry_type' => 'article',
                'citekey' => 'Sh:2',
                'title' => '{Note on a min-max problem of Leo Moser}',
                'author' => 'Shelah, Saharon',
                'editor' => NULL,
                'journal' => 'Journal of Combinatorial Theory',
                'year' => '1969',
                'pages' => '298--300',
                'volume' => '6',
                'number' => NULL,
                'booktitle' => NULL,
                'publisher' => NULL,
                'address' => NULL,
                'misc' => NULL,
                'howpublished' => NULL,
                'annote' => NULL,
                'chapter' => NULL,
                'crossref' => NULL,
                'edition' => NULL,
                'institution' => NULL,
                'key' => NULL,
                'month' => NULL,
                'note' => NULL,
                'organization' => NULL,
                'school' => NULL,
                'series' => NULL,
                'user_id' => $user->id,
                'created_at' => '2019-03-08 13:35:01',
                'updated_at' => '2019-03-08 13:35:01',
            ),
            2 =>
            array (
                'id' => 1320,
                'entry_type' => 'article',
                'citekey' => 'Sh:3',
                'title' => '{Finite diagrams stable in power}',
                'author' => 'Shelah, Saharon',
                'editor' => NULL,
                'journal' => 'Annals of Mathematical Logic',
                'year' => '1970',
                'pages' => '69--118',
                'volume' => '2',
                'number' => NULL,
                'booktitle' => NULL,
                'publisher' => NULL,
                'address' => NULL,
                'misc' => NULL,
                'howpublished' => NULL,
                'annote' => NULL,
                'chapter' => NULL,
                'crossref' => NULL,
                'edition' => NULL,
                'institution' => NULL,
                'key' => NULL,
                'month' => NULL,
                'note' => NULL,
                'organization' => NULL,
                'school' => NULL,
                'series' => NULL,
                'user_id' => $user->id,
                'created_at' => '2019-03-08 13:35:01',
                'updated_at' => '2019-03-08 13:35:01',
            ),
            3 =>
            array (
                'id' => 1321,
                'entry_type' => 'article',
                'citekey' => 'Sh:4',
                'title' => '{On theories $T$ categorical in $|T|$}',
                'author' => 'Shelah, Saharon',
                'editor' => NULL,
                'journal' => 'Journal of Symbolic Logic',
                'year' => '1970',
                'pages' => '73--82',
                'volume' => '35',
                'number' => NULL,
                'booktitle' => NULL,
                'publisher' => NULL,
                'address' => NULL,
                'misc' => NULL,
                'howpublished' => NULL,
                'annote' => NULL,
                'chapter' => NULL,
                'crossref' => NULL,
                'edition' => NULL,
                'institution' => NULL,
                'key' => NULL,
                'month' => NULL,
                'note' => NULL,
                'organization' => NULL,
                'school' => NULL,
                'series' => NULL,
                'user_id' => $user->id,
                'created_at' => '2019-03-08 13:35:01',
                'updated_at' => '2019-03-08 13:35:01',
            ),
            4 =>
            array (
                'id' => 1322,
                'entry_type' => 'article',
                'citekey' => 'Sh:5',
                'title' => '{On languages with non-homogeneous strings of quantifiers}',
                'author' => 'Shelah, Saharon',
                'editor' => NULL,
                'journal' => 'Israel Journal of Mathematics',
                'year' => '1970',
                'pages' => '75--79',
                'volume' => '8',
                'number' => NULL,
                'booktitle' => NULL,
                'publisher' => NULL,
                'address' => NULL,
                'misc' => NULL,
                'howpublished' => NULL,
                'annote' => NULL,
                'chapter' => NULL,
                'crossref' => NULL,
                'edition' => NULL,
                'institution' => NULL,
                'key' => NULL,
                'month' => NULL,
                'note' => NULL,
                'organization' => NULL,
                'school' => NULL,
                'series' => NULL,
                'user_id' => $user->id,
                'created_at' => '2019-03-08 13:35:01',
                'updated_at' => '2019-03-08 13:35:01',
            ),
            5 =>
            array (
                'id' => 1323,
                'entry_type' => 'article',
                'citekey' => 'Sh:6',
                'title' => '{A note on Hanf numbers}',
                'author' => 'Shelah, Saharon',
                'editor' => NULL,
                'journal' => 'Pacific Journal of Mathematics',
                'year' => '1970',
                'pages' => '541--545',
                'volume' => '34',
                'number' => NULL,
                'booktitle' => NULL,
                'publisher' => NULL,
                'address' => NULL,
                'misc' => NULL,
                'howpublished' => NULL,
                'annote' => NULL,
                'chapter' => NULL,
                'crossref' => NULL,
                'edition' => NULL,
                'institution' => NULL,
                'key' => NULL,
                'month' => NULL,
                'note' => NULL,
                'organization' => NULL,
                'school' => NULL,
                'series' => NULL,
                'user_id' => $user->id,
                'created_at' => '2019-03-08 13:35:01',
                'updated_at' => '2019-03-08 13:35:01',
            ),
        ));
    }
}
