language: php

php:
    - '7.2'
    - '7.3'

services:
    - postgresql

matrix:
    include:
        - addons:
            postgresql: 9.6
            apt:
                packages:
                    - postgresql-9.6-postgis-2.4
          dist: xenial
        - addons:
            postgresql: 9.6
            apt:
                packages:
                    - postgresql-9.6-postgis-2.5
          dist: xenial
        - addons:
            postgresql: 10
            apt:
                packages:
                    - postgresql-10-postgis-2.5
          dist: bionic
        - addons:
            postgresql: 10
            apt:
                packages:
                    - postgresql-10-postgis-3
          dist: bionic
        - addons:
            postgresql: 11
            apt:
                packages:
                    - postgresql-11-postgis-2.5
          dist: bionic
        - addons:
            postgresql: 11
            apt:
                packages:
                    - postgresql-11-postgis-3
          dist: bionic
        - addons:
            postgresql: 12
            apt:
                packages:
                    - postgresql-12-postgis-2.5
          dist: bionic
        - addons:
            postgresql: 12
            apt:
                packages:
                    - postgresql-12-postgis-3
          dist: bionic

addons:
  apt:
    packages:
    - gdal-bin

before_script:
    - mkdir -p build/logs
    - cp .env.travis .env.testing
    - psql -c 'create database myapp_test;' -U postgres
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate --env=testing
    - php artisan jwt:secret --env=testing
    - php artisan migrate --env=testing
    - php artisan db:seed --class=DemoSeeder --env=testing

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/php-coveralls -v
