codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto
        if_ci_failed: error

comment: false