export const bibliographyTypes = [
    {
        name: 'article',
        id: 0,
        fields: [
            'abstract',
            'author',
            'doi',
            'email',
            'issn',
            'journal',
            'language',
            'month',
            'note',
            'number',
            'pages',
            'title',
            'url',
            'volume',
            'year',
        ],
        mandatory: {
            author: true,
            title: true,
            journal: true,
            year: true,
        },
    },
    {
        name: 'book',
        id: 1,
        fields: [
            'abstract',
            'address',
            'author',
            'doi',
            'edition',
            'editor',
            'email',
            'isbn',
            'language',
            'month',
            'note',
            'publisher',
            'series',
            'title',
            'url',
            'year',
        ],
        mandatory: {
            author: 'editor',
            editor: 'author',
            title: true,
            publisher: true,
            year: true,
        },
    },
    {
        name: 'incollection',
        id: 2,
        fields: [
            'abstract',
            'address',
            'author',
            'booktitle',
            'chapter',
            'doi',
            'edition',
            'editor',
            'email',
            'language',
            'month',
            'note',
            'number',
            'organization',
            'pages',
            'publisher',
            'series',
            'title',
            'url',
            'volume',
            'year',
        ],
        mandatory: {
            author: true,
            title: true,
            booktitle: true,
            publisher: true,
            year: true,
        },
    },
    {
        name: 'misc',
        id: 3,
        fields: [
            'abstract',
            'author',
            'doi',
            'email',
            'howpublished',
            'language',
            'month',
            'note',
            'title',
            'url',
            'year',
        ]
    },
    {
        name: 'booklet',
        id: 4,
        fields: [
            'abstract',
            'address',
            'author',
            'doi',
            'email',
            'howpublished',
            'language',
            'month',
            'note',
            'title',
            'url',
            'year',
        ],
        mandatory: {
            title: true,
        },
    },
    {
        name: 'conference',
        id: 5,
        fields: [
            'abstract',
            'address',
            'author',
            'booktitle',
            'doi',
            'editor',
            'email',
            'language',
            'month',
            'note',
            'number',
            'organization',
            'pages',
            'publisher',
            'series',
            'title',
            'url',
            'volume',
            'year',
        ],
        mandatory: {
            author: true,
            booktitle: true,
            title: true,
            year: true,
        },
    },
    {
        name: 'inbook',
        id: 6,
        fields: [
            'abstract',
            'address',
            'author',
            'chapter',
            'doi',
            'edition',
            'editor',
            'email',
            'isbn',
            'language',
            'month',
            'note',
            'number',
            'pages',
            'publisher',
            'series',
            'title',
            'url',
            'volume',
            'year',
        ],
        mandatory: {
            author: 'editor',
            chapter: 'pages',
            editor: 'author',
            pages: 'chapter',
            publisher: true,
            title: true,
            year: true,
        },
    },
    {
        name: 'inproceedings',
        id: 7,
        fields: [
            'abstract',
            'address',
            'author',
            'booktitle',
            'doi',
            'editor',
            'email',
            'language',
            'month',
            'note',
            'number',
            'organization',
            'pages',
            'publisher',
            'series',
            'title',
            'url',
            'volume',
            'year',
        ],
        mandatory: {
            author: true,
            booktitle: true,
            title: true,
            year: true,
        },
    },
    {
        name: 'manual',
        id: 8,
        fields: [
            'abstract',
            'address',
            'author',
            'doi',
            'edition',
            'email',
            'language',
            'month',
            'note',
            'organization',
            'title',
            'url',
            'year',
        ],
        mandatory: {
            title: true,
        },
    },
    {
        name: 'mastersthesis',
        id: 9,
        fields: [
            'abstract',
            'address',
            'author',
            'doi',
            'email',
            'language',
            'month',
            'note',
            'school',
            'title',
            'type',
            'url',
            'year',
        ],
        mandatory: {
            author: true,
            school: true,
            title: true,
            year: true,
        },
    },
    {
        name: 'phdthesis',
        id: 10,
        fields: [
            'abstract',
            'address',
            'author',
            'doi',
            'email',
            'language',
            'month',
            'note',
            'school',
            'title',
            'type',
            'url',
            'year',
        ],
        mandatory: {
            author: true,
            school: true,
            title: true,
            year: true,
        },
    },
    {
        name: 'proceedings',
        id: 11,
        fields: [
            'abstract',
            'address',
            'doi',
            'editor',
            'email',
            'language',
            'month',
            'note',
            'number',
            'organization',
            'publisher',
            'series',
            'title',
            'url',
            'volume',
            'year',
        ],
        mandatory: {
            title: true,
            year: true,
        },
    },
    {
        name: 'techreport',
        id: 12,
        fields: [
            'abstract',
            'address',
            'author',
            'doi',
            'email',
            'institution',
            'language',
            'month',
            'note',
            'number',
            'title',
            'url',
            'year',
        ],
        mandatory: {
            author: true,
            institution: true,
            title: true,
            year: true,
        },
    },
    {
        name: 'unpublished',
        id: 13,
        fields: [
            'abstract',
            'author',
            'email',
            'language',
            'month',
            'note',
            'title',
            'url',
            'year',
        ],
        mandatory: {
            author: true,
            note: true,
            title: true,
        },
    }
];

export const formatAuthors = (authors, count = 3) => {
    if(!authors) return authors;

    const authorList = authors.trim().split(/\s+and\s+/g);
    let authorNameList = authorList.map(author => formatAuthorName(author));

    // only add 'et. al.' to `count` or more authors
    // otherwise return original authors
    if(authorNameList.length === 0) {
        return authors;
    } else if(authorNameList.length === 1) {
        return authorNameList[0];
    } else if(authorNameList.length >= 2 && authorList.length <= count) {
        const lastAuthor = authorNameList.pop();
        return authorNameList.join(', ') + ' & ' + lastAuthor;
    }

    return authorNameList.slice(0, count).join(', ') + ' et al.';
};

export const formatAuthorName = (author) => {
    let names = author.split(/\s*,\s*/g);
    return names.reverse().join(' ');
};

export const formatBibtexText = text => {
    if(!text) return '';
    return text.replace(/[\{\}]/g, '');
};
